worker_processes auto;
rtmp_auto_push on;
events {}

rtmp {
    server {
        listen 1935;
        listen [::]:1935 ipv6only=on;

        application live {
            live on;
            record off;
            hls on;
            hls_cleanup on;

            hls_path /tmp/hls; 
            hls_fragment 1s; #default is 5s
            hls_playlist_length 20s; # default is 30s
            # once playlist length is reached it deletes the oldest fragments

        }
    }
}

http {
    server {
        listen 8080;

        location / {
            root /www;
        }

        location /hls{
            types{
                application/vnd.apple.mpegurl m3u8;
                application/octet-stream ts;
            }

            root /tmp;
            add_header Cache-Control no-cache;

            # To avoid issues with cross-domain HTTP requests (e.g. during development)
            add_header Access-Control-Allow-Origin *;
        }

        # 提供 WebM stream
        location /live/ {
            root /tmp;
            client_max_body_size 0;
            proxy_buffering off;         # 禁用緩衝
            chunked_transfer_encoding on;# 啟用分塊傳輸編碼
            client_body_timeout 3600s;   # 客戶端超時設置為 1 小時
            keepalive_timeout 3600s;     # 長連接保持時間
            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
            types {
                video/webm webm;
            }
        }
    }
}

# ffmpeg -i rtmp://localhost/live/test \
#     -c:v libvpx-vp9 -c:a libopus \
#     -f webm \
#     -fflags nobuffer \
#     -flags low_delay \
#     /tmp/live/test.webm